package d20_staticblock_instanceblock_oop;

public class AnimalRunner {
    public static void main(String[] args) {
        Dog d = new Dog();
        d.bark(); // Dogs bark...
        d.feedWithMilk(); // Mammals feed their babies with milk...
        d.drink(); // Animals drink...
        d.eat(); // Animals eat...

        Bird b = new Bird();
        b.tweet(); // Birds tweet...
        b.drink(); // Animals drink...
        b.eat(); // Animals eat...

        Cat c = new Cat();
        c.meow(); // Cats meow...
        c.feedWithMilk(); // Mammals feed their babies with milk...
        c.drink(); // Animals drink...
        c.eat(); // Animals eat...

        Mammal m = new Mammal();
        m.feedWithMilk(); // Mammals feed their babies with milk...
        m.drink(); // Animals drink...
        m.eat(); // Animals eat...

        // a) Java ‘Multiple Inheritance’ i desteklemez. ‘Single Inheritance’ i destekler

        // b) Parent ve birden fazla child ile olusturulan inheritance yapilanmasina
        //    'Hierarchical Inheritance' denir ve Java bunu kabul eder.

        /* c) Ama coklu parent'lardan yararlanamamak iyi olmadi. Ozelliklerini inherit etmek istedigimiz class'lar
        birden fazla ise (parent'lar) o durumda Java bize, Apartman tarzi yapilanma olusturmustur.
        ( 'Multi Level Inheritance') Java bunu kabul eder. */

        // Java’da parent’tan child’a olan iliskilere HAS-A Relationship denir(yukaridan asagiya)
        // Java’da child’tan parent’a olan iliskilere IS-A Relationship denir (asagidan yukariya)
    }
}
